package co.com.acueducto.sgda.jbpm.modelo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class SolicitudPQRS implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SOLICITUDPQRS_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "SOLICITUDPQRS_ID_GENERATOR", sequenceName = "SOLICITUDPQRS_ID_SEQ")
    private java.lang.Long id;

    public SolicitudPQRS() {
    }
    
    public SolicitudPQRS(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}