package co.com.acueducto.sgda.jbpm.modelo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Usuario implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Usuario")
	private java.lang.String usuario;
	@org.kie.api.definition.type.Label("Actividad")
	private java.lang.String actividad;
	@org.kie.api.definition.type.Label("Aprueba Respuesta?")
	private java.lang.Boolean aprobacionFlag;
	@org.kie.api.definition.type.Label("Fecha Aprobación")
	private java.lang.String fechaAprobacion;
	@org.kie.api.definition.type.Label("Fecha Asignación")
	private java.lang.String fechaAsignacion;

	@org.kie.api.definition.type.Label(value = "Causal de Rechazo")
	private java.lang.String aprobacionRechazoCausal;

	@org.kie.api.definition.type.Label(value = "Causal Otro")
	private java.lang.String aprobacionRechazoOtro;

	@org.kie.api.definition.type.Label(value = "Observaciones")
	private java.lang.String aprobacionRechazoObs;

	public Usuario() {
	}

	public java.lang.String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(java.lang.String usuario) {
		this.usuario = usuario;
	}

	public java.lang.String getActividad() {
		return this.actividad;
	}

	public void setActividad(java.lang.String actividad) {
		this.actividad = actividad;
	}

	public java.lang.Boolean getAprobacionFlag() {
		return this.aprobacionFlag;
	}

	public void setAprobacionFlag(java.lang.Boolean aprobacionFlag) {
		this.aprobacionFlag = aprobacionFlag;
	}

	public java.lang.String getFechaAprobacion() {
		return this.fechaAprobacion;
	}

	public void setFechaAprobacion(java.lang.String fechaAprobacion) {
		this.fechaAprobacion = fechaAprobacion;
	}

	public java.lang.String getFechaAsignacion() {
		return this.fechaAsignacion;
	}

	public void setFechaAsignacion(java.lang.String fechaAsignacion) {
		this.fechaAsignacion = fechaAsignacion;
	}

	@Override
	public String toString() {

		Gson gson = new GsonBuilder().setPrettyPrinting().create();
		return gson.toJson(this);
	}

	public java.lang.String getAprobacionRechazoCausal() {
		return this.aprobacionRechazoCausal;
	}

	public void setAprobacionRechazoCausal(
			java.lang.String aprobacionRechazoCausal) {
		this.aprobacionRechazoCausal = aprobacionRechazoCausal;
	}

	public java.lang.String getAprobacionRechazoOtro() {
		return this.aprobacionRechazoOtro;
	}

	public void setAprobacionRechazoOtro(java.lang.String aprobacionRechazoOtro) {
		this.aprobacionRechazoOtro = aprobacionRechazoOtro;
	}

	public java.lang.String getAprobacionRechazoObs() {
		return this.aprobacionRechazoObs;
	}

	public void setAprobacionRechazoObs(java.lang.String aprobacionRechazoObs) {
		this.aprobacionRechazoObs = aprobacionRechazoObs;
	}

	public Usuario(java.lang.String usuario, java.lang.String actividad,
			java.lang.Boolean aprobacionFlag, java.lang.String fechaAprobacion,
			java.lang.String fechaAsignacion,
			java.lang.String aprobacionRechazoCausal,
			java.lang.String aprobacionRechazoOtro,
			java.lang.String aprobacionRechazoObs) {
		this.usuario = usuario;
		this.actividad = actividad;
		this.aprobacionFlag = aprobacionFlag;
		this.fechaAprobacion = fechaAprobacion;
		this.fechaAsignacion = fechaAsignacion;
		this.aprobacionRechazoCausal = aprobacionRechazoCausal;
		this.aprobacionRechazoOtro = aprobacionRechazoOtro;
		this.aprobacionRechazoObs = aprobacionRechazoObs;
	}
}